EmployeeDirectory/EmployeeDirectory/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmployeeDirectory.Utilities;
using PagedList;
using EmployeeDirectory.Models;
using EmployeeDirectory.DAL;

namespace EmployeeDirectory.Controllers
{
    public class EmployeeController : Controller
    {
        private EmployeeContext context = new EmployeeContext();
        private EmployeeRepository employeeRepository = new EmployeeRepository();
        private readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: /Employee/

         [Authorize]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.LastNameSortParm = String.IsNullOrEmpty(sortOrder) ? "last_name" : "";
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(sortOrder) ? "first_name" : "";
            //ViewBag.FirsttNameSortParm = sortOrder == "FirstName" ? "first_name" : "FirstName";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var employees = context.Employees.AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                employees = employeeRepository.SelectEmployees(searchString);
                //employees = employees.Where(s => s.FirstName.Contains(searchString)
                //    || s.LastName.Contains(searchString));
           }
            switch (sortOrder)
            {
                case "last_name":
                    employees = employees.OrderBy(s => s.LastName);
                    break;
                case "first_name":
                    employees = employees.OrderBy(s => s.FirstName);
                    break;
                default:  // Name ascending 
                    employees = employees.OrderBy(s => s.LastName);
                    break;
            }
           

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(employees.ToPagedList(pageNumber, pageSize));

            //return View(db.Employees.ToList());
        }

        // GET: /Employee/Details/5
         [Authorize(Roles = "ApplicationUser")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = context.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: /Employee/Create
       [Authorize]
        public ActionResult Create()
        {
            //Get list of states..
            var states = UnitedStates.States;
            var titles = context.Titles.ToList().Select(c => new SelectListItem
            {
                Value = c.id.ToString(),
                Text = c.JobTitle
            });

            var model = new Employee();
            model.States = states;
            model.Titles = titles;
            return View(model);
        }

        // POST: /Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,LastName,FirstName,MiddleName,TitleId,Address1,Address2,City,State,Zip,Email,PhoneWork,PhoneCell")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    employee.CreatedBy = (Guid)Common.GetCurrentUserId();
                    employee.CreatedOn = DateTime.Now;
                    context.Employees.Add(employee);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    logger.Error(ex.Message); 
                    //logger.Info(ex.Message);
                }
              
            }

            return View(employee);
        }

        // GET: /Employee/Edit/5
          [Authorize(Roles = "HRUser")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = context.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            //Get list of states..
            var states = UnitedStates.States;
            var titles = context.Titles.ToList().Select(c => new SelectListItem
            {
                Value = c.id.ToString(),
                Text = c.JobTitle
            });

         
            ViewBag.State = states;
            ViewBag.Titles = titles;
            var model = new Employee();
            employee.States = states;
            employee.Titles = titles;
            return View(employee);
        }

        // POST: /Employee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
          public ActionResult Edit([Bind(Include = "Id,LastName,FirstName,MiddleName,TitleId,Address1,Address2,City,State,Zip,Email,PhoneWork,PhoneCell,CreatedBy,CreatedOn")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.ModifiedBy = (Guid)Common.GetCurrentUserId();
                employee.ModifiedOn = DateTime.Now;
                
                Employee emp = context.Employees.Find(employee.Id);
                employee.CreatedOn = emp.CreatedOn;
                employee.CreatedBy = emp.CreatedBy;
                ((IObjectContextAdapter)context).ObjectContext.Detach(emp);
                context.Entry(employee).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: /Employee/Delete/5
          [Authorize(Roles = "HRUser")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = context.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: /Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = context.Employees.Find(id);
            context.Employees.Remove(employee);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmployeeDirectory/EmployeeDirectory/Views/Employee/Create.cshtml
@model EmployeeDirectory.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Title, // 1. Store selected value in Model.State;
                 Model.Titles,
                    "- Please select a Title -",
                new { @class = "form-control" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName)
                @Html.ValidationMessageFor(model => model.MiddleName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1)
                @Html.ValidationMessageFor(model => model.Address1)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Address2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2)
                @Html.ValidationMessageFor(model => model.Address2)
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>*@
        
        @* State selection dropdown *@
        <div class="form-group">
            @Html.LabelFor(m => m.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.State, // 1. Store selected value in Model.State;
                    // when page is rendered after postback,
                    // take selected value from Model.State.

                    // 2. Take list of values from Model.States
                    Model.States,

                    // 3. Text for the first 'default' option
                    "- Please select a state -",

                    //4. A class name to assign to <select> tag
                    new { @class = "form-control" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Zip, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip)
                @Html.ValidationMessageFor(model => model.Zip)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneWork, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneWork)
                @Html.ValidationMessageFor(model => model.PhoneWork)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneCell, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneCell)
                @Html.ValidationMessageFor(model => model.PhoneCell)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.StatusId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StatusId)
                @Html.ValidationMessageFor(model => model.StatusId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy)
                @Html.ValidationMessageFor(model => model.CreatedBy)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOn)
                @Html.ValidationMessageFor(model => model.CreatedOn)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy)
                @Html.ValidationMessageFor(model => model.ModifiedBy)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedOn, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedOn)
                @Html.ValidationMessageFor(model => model.ModifiedOn)
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeDirectory/EmployeeDirectory/Views/Employee/Delete.cshtml
@model EmployeeDirectory.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneWork)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneWork)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneCell)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneCell)
        </dd>
       
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EmployeeDirectory/EmployeeDirectory/Views/Employee/Details.cshtml
@model EmployeeDirectory.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneWork)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneWork)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneCell)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneCell)
        </dd>

     

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EmployeeDirectory/EmployeeDirectory/Views/Employee/Edit.cshtml
@model EmployeeDirectory.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        
        <div class="form-group">
            @Html.LabelFor(model => model.TitleId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.TitleId,
              (IEnumerable<SelectListItem>)ViewBag.Titles, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.DropDownListFor(m => m.Title, // 1. Store selected value in Model.State;
                    Model.Titles,
                    "- Please select a Title -",
                    new { @class = "form-control" })*@
            </div>
           </div> 

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName)
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName)
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MiddleName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MiddleName)
                    @Html.ValidationMessageFor(model => model.MiddleName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address1, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address1)
                    @Html.ValidationMessageFor(model => model.Address1)
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.Address2, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address2)
                    @Html.ValidationMessageFor(model => model.Address2)
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City)
                    @Html.ValidationMessageFor(model => model.City)
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.State)
                    @Html.ValidationMessageFor(model => model.State)
                </div>
            </div>*@
        
        @* State selection dropdown *@
        <div class="form-group">
            @Html.LabelFor(m => m.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.State,
               (IEnumerable<SelectListItem>)ViewBag.State, new { htmlAttributes = new { @class = "form-control" } })


                @*@Html.DropDownListFor(m => m.State, // 1. Store selected value in Model.State;
                    // when page is rendered after postback,
                    // take selected value from Model.State.

                    // 2. Take list of values from Model.States
                    Model.States,

                    // 3. Text for the first 'default' option
                    "- Please select a state -",

                    //4. A class name to assign to <select> tag
                    new { @class = "form-control" })*@
            </div>
        </div>

        <div class="form-group">
                @Html.LabelFor(model => model.Zip, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Zip)
                    @Html.ValidationMessageFor(model => model.Zip)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneWork, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneWork)
                    @Html.ValidationMessageFor(model => model.PhoneWork)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneCell, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneCell)
                    @Html.ValidationMessageFor(model => model.PhoneCell)
                </div>
            </div>



            @*<div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy)
                    @Html.ValidationMessageFor(model => model.CreatedBy)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedOn, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedOn)
                    @Html.ValidationMessageFor(model => model.CreatedOn)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedBy, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedBy)
                    @Html.ValidationMessageFor(model => model.ModifiedBy)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedOn, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedOn)
                    @Html.ValidationMessageFor(model => model.ModifiedOn)
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeDirectory/EmployeeDirectory/Views/Employee/Index.cshtml
@model PagedList.IPagedList<EmployeeDirectory.Models.Employee>
@using EmployeeDirectory.Utilities
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
@{
    ViewBag.Title = "Index";
}
@helper Truncate(string input, int length)
{
    if (!string.IsNullOrEmpty(input))
    {
        if (input.Length <= length)
        {
            @input
        }
        else
        {
            @input.Substring(0, length)<a href="#"> ...</a>
        }

    }

}


<h2>Index</h2>
@if (this.IsAdmin())
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
@using (Html.BeginForm("Index", "Employee", FormMethod.Get))
{
    @*@Html.HiddenFor(m => m.id)*@
    <p>
      
        Find Employee: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
       

        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    @if (Model.Any())
    {
        <tr>
            <th>
                @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
        
       
            <th>
                @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })


            </th>
          
            <th>
                Address
            </th>

            <th>
                City
            </th>
            <th>
                State
            </th>
            <th>
                Zip
            </th>
            <th>
                Email
            </th>
            <th>
                Work #
            </th>
            <th>
                Mobile #
            </th>

            <th></th>
        </tr>
    }
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
              
                <td>
                    @Html.DisplayFor(modelItem => item.Address1)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Zip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneWork)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneCell)
                </td>

                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) 
                    @if (this.IsAdmin())
                    {

                        @Html.Raw("| ")  @Html.ActionLink("Edit", "Edit", new { id = item.Id }) @Html.Raw(" | ")
                       @Html.ActionLink("Delete", "Delete", new { id = item.Id }) 

                }
                    

                    
                </td>
            </tr>
    }

    </table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
<div id="dialog-edit" style="display: none"></div>
<script src="~/Scripts/Custom/partialview.js"></script>